# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 12:54
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20180223_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
