# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kagiso_auth', '0008_auto_20160112_0817'),
        ('reddit', '0004_auto_20180227_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('kagisouser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('kagiso_auth.kagisouser',),
        ),
    ]
