# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import reddit.models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0007_auto_20180417_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/radio_com/%Y/%m/%d/', validators=[reddit.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/radio_com/%Y/%m/%d/', validators=[reddit.models.validate_image]),
        ),
    ]
