# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0008_auto_20180420_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image_compress_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='submission',
            name='image_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
