# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0009_auto_20180420_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_compress_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
